const mongoDB = require("../../db");
const Lesson = require("../../models/lessons/lessons");

// Function to create test lessons (Commented out)
const createTestLessons = async () => {
  try {
    await mongoDB(); // Establish a MongoDB connection

    const userId = "64b5285e6384f51d63b4dbcd"; // Sample user ID

    const sampleLessons = [
      // Sample lessons data
      {
        userId,
        topic: "Redux/RTK",
        subtopic: "Introduction to Redux",
        flashcardsCount: 45,
        lessonDate: new Date(2023, 8, 1, 0, 0),
        endTime: new Date(2023, 8, 2, 0, 0),
        lessonNumber: 3,
        lessonDuration: 45,
        completed: false,
        language: "React",
        points: 1,
      },
      {
        userId,
        topic: "Redux",
        subtopic: "Redux actions",
        flashcardsCount: 45,
        lessonDate: new Date(2023, 8, 2, 10, 0),
        endTime: new Date(2023, 8, 3, 0, 0),
        lessonNumber: 3,
        lessonDuration: 45,
        completed: false,
        language: "React",
        points: 1,
      },
      {
        userId,
        topic: "Redux/RTK",
        subtopic: "Redux selectors",
        flashcardsCount: 45,
        lessonDate: new Date(2023, 8, 3, 0, 0),
        endTime: new Date(2023, 8, 4, 0, 0),
        lessonNumber: 3,
        lessonDuration: 45,
        completed: false,
        language: "React",
        points: 1,
      },
      {
        userId,
        topic: "Redux/RTK",
        subtopic: "Redux slices",
        flashcardsCount: 45,
        lessonDate: new Date(2023, 8, 4, 0, 0),
        endTime: new Date(2023, 8, 5, 0, 0),
        lessonNumber: 3,
        lessonDuration: 45,
        completed: false,
        language: "React",
        points: 1,
      },
      {
        userId,
        topic: "Redux/RTK",
        subtopic: "Redux slices",
        flashcardsCount: 45,
        lessonDate: new Date(2023, 8, 5, 0, 0),
        endTime: new Date(2023, 8, 6, 0, 0),
        lessonNumber: 3,
        lessonDuration: 45,
        completed: false,
        language: "React",
        points: 1,
      },
      {
        userId,
        topic: "Redux/RTK",
        subtopic: "Redux slices",
        flashcardsCount: 45,
        lessonDate: new Date(2023, 8, 6, 0, 0),
        endTime: new Date(2023, 8, 8, 0, 0),
        lessonNumber: 3,
        lessonDuration: 45,
        completed: false,
        language: "React",
        points: 1,
      },
      {
        userId,
        topic: "Redux/RTK",
        subtopic: "Redux slices",
        flashcardsCount: 45,
        lessonDate: new Date(2023, 8, 7, 0, 0),
        endTime: new Date(2023, 8, 8, 0, 0),
        lessonNumber: 3,
        lessonDuration: 45,
        completed: false,
        language: "React",
        points: 1,
      },
      {
        userId,
        topic: "Redux/RTK",
        subtopic: "Redux slices",
        flashcardsCount: 45,
        lessonDate: new Date(2023, 8, 8, 0, 0),
        endTime: new Date(2023, 8, 9, 0, 0),
        lessonNumber: 3,
        lessonDuration: 45,
        completed: false,
        language: "React",
        points: 1,
      },
      {
        userId,
        topic: "Redux/RTK",
        subtopic: "Redux slices",
        flashcardsCount: 45,
        lessonDate: new Date(2023, 8, 9, 0, 0),
        endTime: new Date(2023, 8, 10, 0, 0),
        lessonNumber: 3,
        lessonDuration: 45,
        completed: false,
        language: "React",
        points: 1,
      },
      {
        userId,
        topic: "Redux/RTK",
        subtopic: "Redux slices",
        flashcardsCount: 45,
        lessonDate: new Date(2023, 8, 10, 0, 0),
        endTime: new Date(2023, 8, 11, 0, 0),
        lessonNumber: 3,
        lessonDuration: 45,
        completed: false,
        language: "React",
        points: 1,
      },
      {
        userId,
        topic: "Redux/RTK",
        subtopic: "Redux slices",
        flashcardsCount: 45,
        lessonDate: new Date(2023, 8, 11, 0, 0),
        endTime: new Date(2023, 8, 12, 0, 0),
        lessonNumber: 3,
        lessonDuration: 45,
        completed: false,
        language: "React",
        points: 1,
      },
      {
        userId,
        topic: "Redux/RTK",
        subtopic: "Redux slices",
        flashcardsCount: 45,
        lessonDate: new Date(2023, 8, 12, 0, 0),
        endTime: new Date(2023, 8, 13, 0, 0),
        lessonNumber: 3,
        lessonDuration: 45,
        completed: false,
        language: "React",
        points: 1,
      },
      {
        userId,
        topic: "Redux/RTK",
        subtopic: "Redux slices",
        flashcardsCount: 45,
        lessonDate: new Date(2023, 8, 13, 0, 0),
        endTime: new Date(2023, 8, 14, 0, 0),
        lessonNumber: 3,
        lessonDuration: 45,
        completed: false,
        language: "React",
        points: 1,
      },
      {
        userId,
        topic: "Redux/RTK",
        subtopic: "Redux slices",
        flashcardsCount: 45,
        lessonDate: new Date(2023, 8, 14, 0, 0),
        endTime: new Date(2023, 8, 15, 0, 0),
        lessonNumber: 3,
        lessonDuration: 45,
        completed: false,
        language: "React",
        points: 1,
      },
      {
        userId,
        topic: "Redux/RTK",
        subtopic: "Redux slices",
        flashcardsCount: 45,
        lessonDate: new Date(2023, 8, 15, 0, 0),
        endTime: new Date(2023, 8, 16, 0, 0),
        lessonNumber: 3,
        lessonDuration: 45,
        completed: false,
        language: "React",
        points: 1,
      },
      {
        userId,
        topic: "Redux/RTK",
        subtopic: "Redux slices",
        flashcardsCount: 45,
        lessonDate: new Date(2023, 8, 16, 0, 0),
        endTime: new Date(2023, 8, 17, 0, 0),
        lessonNumber: 3,
        lessonDuration: 45,
        completed: false,
        language: "React",
        points: 1,
      },
      {
        userId,
        topic: "Redux/RTK",
        subtopic: "Redux slices",
        flashcardsCount: 45,
        lessonDate: new Date(2023, 8, 17, 0, 0),
        endTime: new Date(2023, 8, 18, 0, 0),
        lessonNumber: 3,
        lessonDuration: 45,
        completed: false,
        language: "React",
        points: 1,
      },
      {
        userId,
        topic: "Redux/RTK",
        subtopic: "Redux slices",
        flashcardsCount: 45,
        lessonDate: new Date(2023, 8, 18, 0, 0),
        endTime: new Date(2023, 8, 19, 0, 0),
        lessonNumber: 3,
        lessonDuration: 45,
        completed: false,
        language: "React",
        points: 1,
      },
      {
        userId,
        topic: "Redux/RTK",
        subtopic: "Redux slices",
        flashcardsCount: 45,
        lessonDate: new Date(2023, 8, 19, 0, 0),
        endTime: new Date(2023, 8, 20, 0, 0),
        lessonNumber: 3,
        lessonDuration: 45,
        completed: false,
        language: "React",
        points: 1,
      },
      {
        userId,
        topic: "Redux/RTK",
        subtopic: "Redux slices",
        flashcardsCount: 45,
        lessonDate: new Date(2023, 8, 20, 0, 0),
        endTime: new Date(2023, 8, 21, 0, 0),
        lessonNumber: 3,
        lessonDuration: 45,
        completed: false,
        language: "React",
        points: 1,
      },
      {
        userId,
        topic: "Redux/RTK",
        subtopic: "Redux slices",
        flashcardsCount: 45,
        lessonDate: new Date(2023, 8, 21, 0, 0),
        endTime: new Date(2023, 8, 22, 0, 0),
        lessonNumber: 3,
        lessonDuration: 45,
        completed: false,
        language: "React",
        points: 1,
      },
      {
        userId,
        topic: "Redux/RTK",
        subtopic: "Redux slices",
        flashcardsCount: 45,
        lessonDate: new Date(2023, 8, 22, 0, 0),
        endTime: new Date(2023, 8, 23, 0, 0),
        lessonNumber: 3,
        lessonDuration: 45,
        completed: false,
        language: "React",
        points: 1,
      },
      {
        userId,
        topic: "Redux/RTK",
        subtopic: "Redux slices",
        flashcardsCount: 45,
        lessonDate: new Date(2023, 8, 23, 0, 0),
        endTime: new Date(2023, 8, 24, 0, 0),
        lessonNumber: 3,
        lessonDuration: 45,
        completed: false,
        language: "React",
        points: 1,
      },
      {
        userId,
        topic: "Redux/RTK",
        subtopic: "Redux slices",
        flashcardsCount: 45,
        lessonDate: new Date(2023, 8, 24, 0, 0),
        endTime: new Date(2023, 8, 25, 0, 0),
        lessonNumber: 3,
        lessonDuration: 45,
        completed: false,
        language: "React",
        points: 1,
      },
      {
        userId,
        topic: "Redux/RTK",
        subtopic: "Redux slices",
        flashcardsCount: 45,
        lessonDate: new Date(2023, 8, 25, 0, 0),
        endTime: new Date(2023, 8, 26, 0, 0),
        lessonNumber: 3,
        lessonDuration: 45,
        completed: false,
        language: "React",
        points: 1,
      },
      {
        userId,
        topic: "Redux/RTK",
        subtopic: "Redux selectors",
        flashcardsCount: 45,
        lessonDate: new Date(2023, 8, 26, 0, 0),
        endTime: new Date(2023, 8, 27, 0, 0),
        lessonNumber: 3,
        lessonDuration: 45,
        completed: false,
        language: "React",
        points: 1,
      },
      {
        userId,
        topic: "RTK",
        subtopic: "Redux actions",
        flashcardsCount: 45,
        lessonDate: new Date(2023, 8, 27, 0, 0),
        endTime: new Date(2023, 8, 28, 0, 0),
        lessonNumber: 3,
        lessonDuration: 45,
        completed: false,
        language: "React",
        points: 1,
      },
      {
        userId,
        topic: "Redux/RTK",
        subtopic: "Redux slices",
        flashcardsCount: 45,
        lessonDate: new Date(2023, 8, 28, 0, 0),
        endTime: new Date(2023, 8, 29, 0, 0),
        lessonNumber: 3,
        lessonDuration: 45,
        completed: false,
        language: "React",
        points: 1,
      },
      {
        userId,
        topic: "Redux/RTK",
        subtopic: "Redux slices",
        flashcardsCount: 45,
        lessonDate: new Date(2023, 8, 29, 0, 0),
        endTime: new Date(2023, 8, 30, 0, 0),
        lessonNumber: 3,
        lessonDuration: 45,
        completed: false,
        language: "React",
        points: 1,
      },
      {
        userId,
        topic: "Redux/RTK",
        subtopic: "Redux slices",
        flashcardsCount: 45,
        lessonDate: new Date(2023, 8, 30, 0, 0),
        endTime: new Date(2023, 8, 31, 0, 0),
        lessonNumber: 3,
        lessonDuration: 45,
        completed: false,
        language: "React",
        points: 1,
      },
      {
        userId,
        topic: "The last REdux",
        subtopic: "The last redux",
        flashcardsCount: 45,
        lessonDate: new Date(2023, 8, 31, 0, 0),
        endTime: new Date(2023, 8, 1, 0, 0),
        lessonNumber: 3,
        lessonDuration: 45,
        completed: false,
        language: "React",
        points: 1,
      },
    ];

    const deleteLessons = await Lesson.deleteMany({});
    console.log(
      `Удалено ${deleteLessons.deletedCount} документов из коллекции 'Lessons'`
    );

    // Save the sample lessons for the user
    await Lesson.insertMany(sampleLessons);
  } catch (error) {
    console.error(`Error: ${error}`);
  } finally {
    process.exit(1); // Exit the application with a non-zero status code
    console.log("Test lessons has been created");
  }
};

createTestLessons(); // Create test lessons (Commented out)

module.exports = createTestLessons;
