from django.urls import path

from .views import *
from .views_ua import *

urlpatterns = [
    path("", HomePage.as_view(), name="homepage"),
    path("ua/", HomePageUa.as_view(), name="homepage_ua"),
    path("programming-language-choice/", ProgrammingLanguageChoice.as_view(), name="programming_language_choice"),
    path("py/lesson/", PythonLesson.as_view(), name="python_lesson"),
    path("js/lesson/", JavaScriptLesson.as_view(), name="javascript_lesson"),
    path("go/lesson/", GolangLesson.as_view(), name="golang_lesson"),
    path("java/lesson/", JavaLesson.as_view(), name="java_lesson"),
    path("swift/lesson/", SwiftLesson.as_view(), name="swift_lesson"),
    path("php/lesson/", PhpLesson.as_view(), name="php_lesson"),
    path("c-sharp/lesson/", CsharpLesson.as_view(), name="c_sharp_lesson"),
    path("c-plus-plus/lesson/", CplusplusLesson.as_view(), name="c_plus_plus_lesson"),
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(), name="log_in"),
    path("logout/", LogoutView.as_view(), name="log_out"),
    path("tech-writers-page/", TechWritersPage.as_view(), name="tech_writers_page"),
    path("users-homepage/", UsersHomePage.as_view(), name="users_homepage"),
    path("users-store/", UsersStorePage.as_view(), name="users_store"),
    path("pupils-homepage/", PupilsHomePage.as_view(), name="pupils_homepage"),
    path("pupils-event/", PupilsEventPage.as_view(), name="pupils_event"),
    path("pupils-exam/", PupilsExamPage.as_view(), name="pupils_exam"),
    path("pupils-rating/", PupilsRatingPage.as_view(), name="pupils_rating"),
    path("pupils-mentor/", PupilsMentorPage.as_view(), name="pupils_mentor"),
    path("pupils-pvp/", PupilsPvpPage.as_view(), name="pupils_pvp"),
    path("pupils-tvt/", PupilsTvtPage.as_view(), name="pupils_tvt"),
    path("teachers-homepage/", TeachersHomePage.as_view(), name="teachers_homepage"),
    path("teachers-event/", TeachersEventPage.as_view(), name="teachers_event"),
    path("teachers-exam/", TeachersExamPage.as_view(), name="teachers_exam"),
    path("teachers-rating/", TeachersRatingPage.as_view(), name="teachers_rating"),
    path("teachers-mentor/", TeachersMentorPage.as_view(), name="teachers_mentor"),
    path("mentors-homepage/", MentorsHomePage.as_view(), name="mentors_homepage"),
    path("mentors-invocation/", MentorsInvocationPage.as_view(), name="mentors_invocation"),
    path("mentors-session/", MentorsSessionPage.as_view(), name="mentors_session"),
    path("mentors-rating/", MentorsRatingPage.as_view(), name="mentors_rating"),
    path(
        "ua/programming-language-choice/", ProgrammingLanguageChoiceUa.as_view(), name="programming_language_choice_ua"
    ),
    path("ua/py/lesson/", PythonLessonUa.as_view(), name="python_lesson_ua"),
    path("ua/js/lesson/", JavaScriptLessonUa.as_view(), name="javascript_lesson_ua"),
    path("ua/go/lesson/", GolangLessonUa.as_view(), name="golang_lesson_ua"),
    path("ua/java/lesson/", JavaLessonUa.as_view(), name="java_lesson_ua"),
    path("ua/swift/lesson/", SwiftLesson.as_view(), name="swift_lesson_ua"),
    path("ua/php/lesson/", PhpLessonUa.as_view(), name="php_lesson_ua"),
    path("ua/c-sharp/lesson/", CsharpLessonUa.as_view(), name="c_sharp_lesson_ua"),
    path("ua/c-plus-plus/lesson/", CplusplusLesson.as_view(), name="c_plus_plus_lesson_ua"),
    path("ua/register/", RegisterViewUa.as_view(), name="register_ua"),
    path("ua/login/", LoginViewUa.as_view(), name="log_in_ua"),
    path("ua/logout/", LogoutViewUa.as_view(), name="log_out_ua"),
    path("ua/tech-writers-page/", TechWritersPageUa.as_view(), name="tech_writers_page_ua"),
    path("ua/users-homepage/", UsersHomePageUa.as_view(), name="users_homepage_ua"),
    path("ua/users-store/", UsersStorePageUa.as_view(), name="users_store_ua"),
    path("ua/pupils-homepage/", PupilsHomePageUa.as_view(), name="pupils_homepage_ua"),
    path("ua/pupils-event/", PupilsEventPageUa.as_view(), name="pupils_event_ua"),
    path("ua/pupils-exam/", PupilsExamPageUa.as_view(), name="pupils_exam_ua"),
    path("ua/pupils-rating/", PupilsRatingPageUa.as_view(), name="pupils_rating_ua"),
    path("ua/pupils-mentor/", PupilsMentorPageUa.as_view(), name="pupils_mentor_ua"),
    path("ua/pupils-pvp/", PupilsPvpPageUa.as_view(), name="pupils_pvp_ua"),
    path("ua/pupils-tvt/", PupilsTvtPageUa.as_view(), name="pupils_tvt_ua"),
    path("ua/teachers-homepage/", TeachersHomePageUa.as_view(), name="teachers_homepage_ua"),
    path("ua/teachers-event/", TeachersEventPageUa.as_view(), name="teachers_event_ua"),
    path("ua/teachers-exam/", TeachersExamPageUa.as_view(), name="teachers_exam_ua"),
    path("ua/teachers-rating/", TeachersRatingPageUa.as_view(), name="teachers_rating_ua"),
    path("ua/teachers-mentor/", TeachersMentorPageUa.as_view(), name="teachers_mentor_ua"),
    path("ua/mentors-homepage/", MentorsHomePageUa.as_view(), name="mentors_homepage_ua"),
    path("ua/mentors-invocation/", MentorsInvocationPageUa.as_view(), name="mentors_invocation_ua"),
    path("ua/mentors-session/", MentorsSessionPageUa.as_view(), name="mentors_session_ua"),
    path("ua/mentors-rating/", MentorsRatingPageUa.as_view(), name="mentors_rating_ua"),
]
