# Generated by Django 4.0.2 on 2022-03-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joo_tips_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PythonTheoryDataTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.TextField()),
                ('text', models.TextField()),
                ('text_ua', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'python_theory_data_types',
            },
        ),
        migrations.CreateModel(
            name='PythonTheoryVariables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.TextField()),
                ('text', models.TextField()),
                ('text_ua', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'python_theory_variables',
            },
        ),
        migrations.RenameModel(
            old_name='PythonTheory',
            new_name='PythonTheoryBasics',
        ),
        migrations.AlterModelTable(
            name='pythontheorybasics',
            table='python_theory_basics',
        ),
    ]
