# Generated by Django 4.0.4 on 2022-07-18 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joo_tips_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pythonbasicstheoreticaltest',
            old_name='card_id',
            new_name='card',
        ),
    ]
