# Generated by Django 4.0.4 on 2022-04-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joo_tips_app', '0003_pythontheoryaiohttp_pythontheoryarraysrelatedlists_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestsVisitStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guests_ip', models.TextField(null=True)),
                ('guests_location', models.TextField(null=True)),
                ('guests_hostname', models.TextField(null=True)),
                ('visit_date', models.TextField(null=True)),
                ('lets_try_it_date', models.TextField(null=True)),
                ('language', models.TextField(null=True)),
                ('programming_language', models.TextField(null=True)),
                ('users_level', models.TextField(null=True)),
                ('lesson_time', models.TextField(null=True)),
                ('test_time', models.TextField(null=True)),
                ('start_lesson_time', models.TextField(null=True)),
                ('start_test_time', models.TextField(null=True)),
                ('end_theoretical_start_practical_test_time', models.TextField(null=True)),
                ('end_test_time', models.TextField(null=True)),
                ('theoretical_test_result', models.TextField(null=True)),
                ('practical_test_result', models.TextField(null=True)),
                ('register_date', models.TextField(null=True)),
                ('statistic_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'guests_visit_statistic',
            },
        ),
    ]
