# Generated by Django 4.0.4 on 2022-04-20 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joo_tips_app', '0004_guestsvisitstatistic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestsvisitstatistic',
            old_name='users_level',
            new_name='guests_level',
        ),
    ]
